"""Typed schemas and safe parsers for AI Placement Optimization (Phase 1).

AI text is never trusted: every provider response goes through
extract_json_object() plus a strict normalizer before it reaches a route.
Phase 2 will extend this module with the full structured contracts
(template analysis, test plans, action plans); Phase 1 ships the
region-suggestion contract used by the existing region editor.
"""

import json
import re

MAX_SUGGESTIONS = 6

SUGGESTION_TEXT_LIMIT = 500

DEFAULT_EXPECTED_LIFT = '+4%'

_OPENROUTER_RATIONALE = 'Generated by OpenRouter.'


def extract_json_object(text_value):
    """Parse the first JSON object found in model text, or return None.

    Ported from the former app.py helper so all AI parsing lives in the
    service layer.
    """
    text_value = (text_value or '').strip()
    if not text_value:
        return None
    try:
        parsed = json.loads(text_value)
        if isinstance(parsed, dict):
            return parsed
    except Exception:
        pass
    match = re.search(r'\{.*\}', text_value, re.DOTALL)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
        return parsed if isinstance(parsed, dict) else None
    except Exception:
        return None


def _clean_suggestion_text(value):
    text = str(value or '').strip()
    if not text:
        return ''
    return text[:SUGGESTION_TEXT_LIMIT]


def normalize_region_suggestions(raw_suggestions, limit=MAX_SUGGESTIONS, rationale_default=_OPENROUTER_RATIONALE):
    """Normalize model output into the {text, rationale, expected_lift} contract.

    Accepts strings or dicts with at least a non-empty text field; anything
    else is ignored. Returns at most `limit` items.
    """
    normalized = []
    for item in (raw_suggestions or [])[:limit]:
        if isinstance(item, str):
            text = _clean_suggestion_text(item)
            if text:
                normalized.append({'text': text, 'rationale': rationale_default, 'expected_lift': DEFAULT_EXPECTED_LIFT})
        elif isinstance(item, dict) and item.get('text'):
            normalized.append({
                'text': _clean_suggestion_text(item.get('text')),
                'rationale': str(item.get('rationale') or rationale_default)[:500],
                'expected_lift': str(item.get('expected_lift') or DEFAULT_EXPECTED_LIFT),
            })
    return normalized


def validate_region_suggestions_payload(parsed):
    """Validate a parsed provider object against the region-suggestion schema.

    Returns the normalized suggestions list (possibly empty), or None when
    the payload is not a JSON object.
    """
    if not isinstance(parsed, dict):
        return None
    return normalize_region_suggestions(parsed.get('suggestions'))


def validate_object_contract(parsed, required_keys=()):
    """Generic Phase 1 validator for future contracts.

    Returns the parsed dict when it is an object containing every required
    key; otherwise None. Callers must treat None as invalid model output.
    """
    if not isinstance(parsed, dict):
        return None
    for key in required_keys:
        if key not in parsed:
            return None
    return parsed


# ---------------------------------------------------------------------------
# Message Setup placeholder contracts (Phase 3)
# ---------------------------------------------------------------------------

REQUIRED_HEADER_PLACEHOLDERS = ('[date]', '[to]', '[from]', '[subject]', '[test_id]', '[message_id]')

PLACEHOLDER_PATTERN = re.compile(r'\[[a-z_]{2,32}\]')

MAX_MESSAGE_SUGGESTIONS = 3

MESSAGE_TEXT_LIMIT = 5000


def find_placeholders(text_value):
    """Return the set of [placeholder] tokens present in a draft."""
    if not isinstance(text_value, str) or not text_value:
        return set()
    return set(PLACEHOLDER_PATTERN.findall(text_value.lower()))


def normalize_message_suggestions(raw_suggestions, limit=MAX_MESSAGE_SUGGESTIONS):
    """Normalize model output into [{text, rationale}] message drafts.

    Accepts strings or dicts with a non-empty text field; everything else
    is ignored. Text fields are capped at MESSAGE_TEXT_LIMIT characters.
    """
    normalized = []
    for item in (raw_suggestions or [])[:limit]:
        if isinstance(item, str):
            text = item.strip()[:MESSAGE_TEXT_LIMIT]
            if text:
                normalized.append({'text': text, 'rationale': _OPENROUTER_RATIONALE})
        elif isinstance(item, dict) and str(item.get('text') or '').strip():
            normalized.append({
                'text': str(item.get('text')).strip()[:MESSAGE_TEXT_LIMIT],
                'rationale': str(item.get('rationale') or _OPENROUTER_RATIONALE)[:500],
            })
    return normalized


def placeholder_report(original_text, suggested_text, required=()):
    """Compare placeholder coverage between an original draft and a proposal.

    Returns {ok, missing_required, removed}. ok is False when a suggestion
    would drop placeholders that exist in the original or omit any explicitly
    required placeholders.
    """
    original_tokens = find_placeholders(original_text)
    suggested_tokens = find_placeholders(suggested_text)
    removed = sorted(original_tokens - suggested_tokens)
    missing_required = sorted(token for token in required if token not in suggested_tokens)
    return {
        'ok': not removed and not missing_required,
        'removed': removed,
        'missing_required': missing_required,
    }


_MIME_BOUNDARY_SPLIT = re.compile(r'\n[ \t]*\n')

_HTML_DOCUMENT_SIGNAL = re.compile(r'<\s*(!doctype|html|body)\b', re.IGNORECASE)


def analyze_header_structure(header_text):
    """Deterministic sanity checks for a custom header block.

    A valid header block is RFC-style header lines only: no blank lines
    (which start the body/MIME part) and no embedded HTML document.
    """
    header_text = header_text or ''
    problems = []
    if _MIME_BOUNDARY_SPLIT.search(header_text):
        problems.append('header block must not contain blank lines')
    if _HTML_DOCUMENT_SIGNAL.search(header_text):
        problems.append('header block must not contain HTML document tags')
    has_subject = bool(re.search(r'(?:^|\n)\s*Subject\s*:', header_text, re.IGNORECASE))
    return {'problems': problems, 'has_subject': has_subject}


def local_template_analysis(header_text, body_text, body_mode='html'):
    """Deterministic template analysis used when OpenRouter is unavailable."""
    header = header_text or ''
    body = body_text or ''
    structure = analyze_header_structure(header)
    header_tokens = find_placeholders(header)
    body_tokens = find_placeholders(body)
    missing = [token for token in REQUIRED_HEADER_PLACEHOLDERS if token not in header_tokens]
    risks = list(structure['problems'])
    if missing:
        risks.append(f'missing recommended header placeholders: {", ".join(missing)}')
    if len(body) > 20000:
        risks.append('body is very large; placement tests send it verbatim')
    summary = (
        f"Header: {len(header.splitlines())} lines, subject {'present' if structure['has_subject'] else 'missing'}. "
        f"Body ({body_mode}): {len(body)} chars, {len(body_tokens)} placeholder type(s)."
    )
    return {
        'summary': summary,
        'risks': risks,
        'placeholders': sorted(header_tokens | body_tokens),
        'missing_required_placeholders': missing,
        'has_subject': structure['has_subject'],
    }


# ---------------------------------------------------------------------------
# Automated workflow recommendation contracts (Phase 4)
# ---------------------------------------------------------------------------

QUEUE_RISK_LEVELS = ('low', 'review', 'high')

MAX_QUEUE_ITEMS = 100


def _as_str_list(value, limit=12, item_limit=300):
    if not isinstance(value, list):
        return []
    return [str(item)[:item_limit] for item in value[:limit] if str(item or '').strip()]


def normalize_queue_recommendation(parsed, valid_source_ids):
    """Validate an AI queue review against authoritative source ids.

    Unknown/missing ids are dropped; risk values outside low|review|high
    are coerced to 'review'. Returns None when the payload shape is wrong.
    """
    if not isinstance(parsed, dict):
        return None
    valid_ids = {int(sid) for sid in (valid_source_ids or [])}
    items = []
    for item in (parsed.get('queue_items') or [])[:MAX_QUEUE_ITEMS]:
        if not isinstance(item, dict):
            continue
        try:
            source_id = int(item.get('source_id'))
        except (TypeError, ValueError):
            continue
        if source_id not in valid_ids:
            continue
        risk = str(item.get('risk') or 'review').strip().lower()
        items.append({
            'source_id': source_id,
            'risk': risk if risk in QUEUE_RISK_LEVELS else 'review',
            'reason': str(item.get('reason') or '')[:300],
        })
    cleanup = parsed.get('cleanup') if isinstance(parsed.get('cleanup'), dict) else {}
    delete_candidates = []
    try:
        delete_candidates = sorted({int(sid) for sid in (cleanup.get('delete_candidate_ids') or [])
                                    if int(sid) in valid_ids})
    except (TypeError, ValueError):
        delete_candidates = []
    summary = str(parsed.get('summary') or '').strip()[:1000]
    if not summary:
        return None
    return {
        'summary': summary,
        'queue_items': items,
        'cleanup': {'delete_candidate_ids': delete_candidates},
    }


def local_queue_recommendation(queue_items):
    """Deterministic queue risk scoring used when OpenRouter is unavailable."""
    items = []
    delete_candidates = []
    for item in queue_items[:MAX_QUEUE_ITEMS]:
        risk = 'low'
        reasons = []
        if not item.get('has_html_body') and not item.get('has_text_body'):
            risk = 'high'
            reasons.append('no HTML or plain text body captured')
            delete_candidates.append(item.get('source_id'))
        elif not item.get('has_html_body'):
            risk = 'review'
            reasons.append('plain text body only')
        subject_chars = int(item.get('subject_chars') or 0)
        if not subject_chars:
            risk = 'high'
            reasons.append('subject missing')
            delete_candidates.append(item.get('source_id'))
        elif subject_chars > 90:
            if risk == 'low':
                risk = 'review'
            reasons.append(f'subject is long ({subject_chars} chars)')
        if item.get('already_tested'):
            reasons.append(f"last verdict: {item.get('last_verdict') or 'unknown'}")
            if risk == 'low':
                risk = 'review'
        items.append({'source_id': item.get('source_id'), 'risk': risk,
                      'reason': '; '.join(reasons) or 'no structural issues detected'})
    return {
        'summary': (
            f'Local review of {len(items)} queued template(s): '
            f'{sum(1 for i in items if i["risk"] == "high")} high risk, '
            f'{sum(1 for i in items if i["risk"] == "review")} need review. '
            'Delete candidates are proposals only; deletion stays a manual action.'
        ),
        'queue_items': items,
        'cleanup': {'delete_candidate_ids': sorted({sid for sid in delete_candidates if sid})},
    }


def normalize_allocation_recommendation(parsed, allowed_source_types=('manual', 'list')):
    """Validate an AI workspace allocation recommendation.

    Returns None when required fields are missing or types are invalid.
    """
    if not isinstance(parsed, dict) or not str(parsed.get('summary') or '').strip():
        return None
    per_account_raw = parsed.get('recommended_users_per_account')
    recommended_per_account = None
    if per_account_raw is not None:
        try:
            recommended_per_account = max(1, int(per_account_raw))
        except (TypeError, ValueError):
            recommended_per_account = None
    source_type = str(parsed.get('recommended_source_type') or '').strip().lower()
    if source_type and source_type not in allowed_source_types:
        source_type = ''
    return {
        'summary': str(parsed.get('summary'))[:1000].strip(),
        'recommended_users_per_account': recommended_per_account,
        'recommended_source_type': source_type,
        'warnings': _as_str_list(parsed.get('warnings')),
        'coverage_note': str(parsed.get('coverage_note') or '')[:500],
    }


def local_allocation_recommendation(context):
    """Deterministic allocation advice used when OpenRouter is unavailable."""
    accounts = int(context.get('account_count') or 0)
    users_per_account = context.get('users_per_account')
    target_emails = int(context.get('target_emails') or 0)
    recipients = int(context.get('recipient_count') or 0)
    emails = int(context.get('selected_email_count') or 0)
    warnings = []
    if not accounts:
        warnings.append('No Workspace sources selected yet.')
    if not emails:
        warnings.append('No queued templates selected yet.')
    if target_emails and accounts:
        needed_per_account = -(-target_emails // max(1, accounts * max(1, emails)))
        if users_per_account and users_per_account < needed_per_account:
            warnings.append(
                f'Users per account ({users_per_account}) is below the estimated need '
                f'({needed_per_account}) to reach ~{target_emails} test messages.'
            )
    if users_per_account and recipients and users_per_account * max(1, accounts) < recipients:
        warnings.append('Selected senders are fewer than receiving inboxes; coverage will be partial.')
    return {
        'summary': (
            f'With {accounts} source account(s), users-per-account={users_per_account or "all"}, '
            f'{emails} queued email(s), and {recipients} receiving inbox(es).'
        ),
        'recommended_users_per_account': users_per_account,
        'recommended_source_type': '',
        'warnings': warnings or ['No allocation risks detected with current inputs.'],
        'coverage_note': 'Estimates only; the backend recomputes allocations at run time.',
    }


def normalize_readiness_explanation(parsed):
    """Validate an AI readiness explanation; requires a summary string."""
    if not isinstance(parsed, dict) or not str(parsed.get('summary') or '').strip():
        return None
    return {
        'summary': str(parsed.get('summary'))[:1500].strip(),
        'blockers': _as_str_list(parsed.get('blockers')),
        'next_steps': _as_str_list(parsed.get('next_steps')),
        'coverage_estimate': str(parsed.get('coverage_estimate') or '')[:500],
    }


def local_readiness_explanation(context):
    """Deterministic readiness checklist used when OpenRouter is unavailable."""
    blockers = []
    if not context.get('selected_email_count'):
        blockers.append('Select at least one queued template.')
    has_users = bool(context.get('selected_sender_count')) or bool(context.get('users_per_account'))
    if not context.get('account_count') and not context.get('selected_sender_count'):
        blockers.append('Select a Workspace source (account lookup or list) before running.')
    elif not has_users:
        blockers.append('Retrieve or select Workspace sender users first.')
    if not context.get('recipient_count'):
        blockers.append('Select at least one receiving IMAP inbox.')
    estimate = (
        f"~{context.get('estimated_messages', 0)} message(s) planned "
        f"({context.get('strategy') or 'distributed'} strategy)."
    )
    return {
        'summary': (
            f"Ready check: {len(blockers)} blocker(s). {estimate}"
            if blockers else f"All prerequisites look satisfied. {estimate}"
        ),
        'blockers': blockers,
        'next_steps': [f'Resolve: {blocker}' for blocker in blockers][:6],
        'coverage_estimate': estimate,
    }


def normalize_result_analysis(parsed, valid_senders=None, valid_domains=None):
    """Validate an AI result analysis for one automated test.

    Diagnosis/steps/retry text is capped. Copy-ready lists are intersected
    with the authoritative sender/domain sets observed in DB rows, so the
    model cannot invent addresses. Returns None on a malformed payload.
    """
    if not isinstance(parsed, dict):
        return None
    summary = str(parsed.get('summary') or '').strip()[:1200]
    diagnosis = str(parsed.get('diagnosis') or '').strip()[:2000]
    if not summary and not diagnosis:
        return None
    senders = {str(item).strip().lower() for item in (valid_senders or [])}
    domains = {str(item).strip().lower() for item in (valid_domains or [])}

    def _filtered_list(value, allowed, limit=25):
        items = []
        for item in (value or [])[:limit * 2]:
            text = str(item or '').strip().lower()
            if not text:
                continue
            if allowed and text not in allowed:
                continue
            if text not in items:
                items.append(text)
            if len(items) >= limit:
                break
        return items

    retry_raw = parsed.get('retry_plan') if isinstance(parsed.get('retry_plan'), dict) else {}
    copy_raw = parsed.get('copy_lists') if isinstance(parsed.get('copy_lists'), dict) else {}
    recommended = retry_raw.get('recommended')
    return {
        'summary': summary or diagnosis[:1200],
        'diagnosis': _as_str_list(parsed.get('diagnosis'), limit=8, item_limit=400),
        'next_steps': _as_str_list(parsed.get('next_steps'), limit=8),
        'retry_plan': {
            'recommended': bool(recommended) if recommended is not None else False,
            'steps': _as_str_list(retry_raw.get('steps'), limit=8),
            'warnings': _as_str_list(retry_raw.get('warnings'), limit=6),
        },
        'copy_lists': {
            'inbox_users': _filtered_list(copy_raw.get('inbox_users'), senders),
            'spam_users': _filtered_list(copy_raw.get('spam_users'), senders),
            'inbox_domains': _filtered_list(copy_raw.get('inbox_domains'), domains),
            'spam_domains': _filtered_list(copy_raw.get('spam_domains'), domains),
        },
    }


def local_result_analysis(facts):
    """Deterministic result analysis used when OpenRouter is unavailable."""
    total = int(facts.get('total_messages') or 0)
    inbox_pct = int(facts.get('inbox_pct') or 0)
    spam_pct = int(facts.get('spam_pct') or 0)
    missing_pct = int(facts.get('missing_pct') or 0)
    worst = facts.get('worst_senders') or []
    spam_domains = facts.get('spam_heavy_domains') or []
    errors = facts.get('error_samples') or []
    diagnosis = [
        f"{inbox_pct}% inbox / {spam_pct}% spam / {missing_pct}% unobserved across {total} message(s)."
    ]
    if spam_pct >= 40:
        diagnosis.append('Spam share is high; content and sender reputation both need review.')
    elif inbox_pct >= 80:
        diagnosis.append('Inbox placement is strong for this run.')
    else:
        diagnosis.append('Placement is mixed; compare providers and senders before the next run.')
    if worst:
        diagnosis.append(
            'Highest-spam senders: ' + ', '.join(
                f"{item.get('sender')} ({item.get('spam_pct')}%)" for item in worst[:5]
            ) + '.'
        )
    next_steps = []
    if spam_domains:
        next_steps.append('Review authentication (SPF/DKIM/DMARC) for: ' + ', '.join(
            item.get('domain', '') for item in spam_domains[:5]) + '.')
    if missing_pct >= 20:
        next_steps.append('Re-sync receiving inboxes; many messages are still unobserved.')
    next_steps.append('Copy the healthy sender list below and reuse it as the source set for the next test.')
    retry_recommended = bool(errors) or missing_pct >= 20
    retry_steps = []
    if retry_recommended:
        if errors:
            retry_steps.append('Resolve send errors first: ' + '; '.join(errors[:3]))
        retry_steps.append('Wait for delivery to settle, then press "Sync fresh data" on this test.')
        retry_steps.append('If unobserved messages remain, re-run the same test with the same recipients.')
    warnings = ['Retry is manual: nothing is sent automatically by AI.']
    return {
        'summary': (
            f"Local analysis of {total} message(s): {inbox_pct}% inbox, {spam_pct}% spam, "
            f"{missing_pct}% unobserved."
        ),
        'diagnosis': diagnosis,
        'next_steps': next_steps[:8] or ['No action needed; results look healthy.'],
        'retry_plan': {
            'recommended': retry_recommended,
            'steps': retry_steps,
            'warnings': warnings,
        },
        'copy_lists': {
            'inbox_users': [item.get('sender', '') for item in (facts.get('best_senders') or [])],
            'spam_users': [item.get('sender', '') for item in worst],
            'inbox_domains': [item.get('domain', '') for item in (facts.get('healthy_domains') or [])],
            'spam_domains': [item.get('domain', '') for item in spam_domains],
        },
    }


# ---------------------------------------------------------------------------
# Post-sync AI agent decision contract
# ---------------------------------------------------------------------------

def normalize_post_sync_decision(parsed, valid_grey_users=None, grey_update_enabled=False):
    """Validate an AI decision after app-owned sending/syncing/classification.

    The model may recommend whether to change grey-user names and whether to
    retest, but targets are intersected with authoritative grey users from the
    DB classification. This keeps the AI in the judgment layer while the app
    still owns mutation, safety checks, and execution.
    """
    if not isinstance(parsed, dict):
        return None
    valid_by_email = {}
    for item in valid_grey_users or []:
        if not isinstance(item, dict):
            continue
        email = str(item.get('email') or '').strip().lower()
        if email:
            valid_by_email[email] = item
    raw_targets = parsed.get('grey_user_targets') or parsed.get('targets') or []
    targets = []
    seen = set()
    for item in raw_targets[:100]:
        email = str(item.get('email') if isinstance(item, dict) else item or '').strip().lower()
        if email and email in valid_by_email and email not in seen:
            targets.append(valid_by_email[email])
            seen.add(email)
    requested_change = bool(parsed.get('change_grey_names'))
    change_grey_names = bool(grey_update_enabled and requested_change and targets)
    retry_after_changes = bool(change_grey_names and parsed.get('retry_after_changes'))
    if not grey_update_enabled:
        next_action = 'review_only'
    elif change_grey_names:
        next_action = 'change_grey_names'
    elif valid_by_email:
        next_action = 'skip_grey_changes'
    else:
        next_action = 'complete'
    summary = str(parsed.get('summary') or '').strip()[:1200]
    if not summary:
        summary = 'Post-sync analysis completed.'
    rationale = _as_str_list(parsed.get('rationale'), limit=8, item_limit=400)
    safeguards = _as_str_list(parsed.get('safeguards'), limit=8, item_limit=300)
    if not safeguards:
        safeguards = [
            'The app validates every target against observed grey users before changing names.',
            'The app performs Workspace mutations and retests; AI only returns a decision.',
        ]
    return {
        'summary': summary,
        'next_action': next_action,
        'change_grey_names': change_grey_names,
        'retry_after_changes': retry_after_changes,
        'grey_user_targets': targets,
        'rationale': rationale,
        'safeguards': safeguards,
    }


def local_post_sync_decision(facts):
    """Deterministic fallback for the post-sync agent decision."""
    facts = facts or {}
    grey_update_enabled = bool(facts.get('grey_update_enabled'))
    grey_users = [
        item for item in (((facts.get('classification') or {}).get('lists') or {}).get('grey_users') or [])
        if isinstance(item, dict) and item.get('email') and item.get('service_account_id')
    ]
    change = bool(grey_update_enabled and grey_users)
    return {
        'summary': (
            f"Read {facts.get('test_id') or 'the synced test'}: "
            f"{len(grey_users)} grey user(s) are eligible for safe name changes."
            if change else
            f"Read {facts.get('test_id') or 'the synced test'}: no eligible grey-user update will run."
        ),
        'next_action': 'change_grey_names' if change else ('review_only' if not grey_update_enabled else 'complete'),
        'change_grey_names': change,
        'retry_after_changes': change,
        'grey_user_targets': grey_users,
        'rationale': [
            'Grey-user changes are only useful for senders observed in both inbox and spam.',
            'Only grey users with a loaded Workspace service account are eligible.',
        ],
        'safeguards': [
            'Sending and syncing were completed by the app before this decision.',
            'The app validates every target again before mutation.',
            'Retesting is created by the app only after successful name changes.',
        ],
    }
